import {
  Play, MessageSquare, Palette, Swords, Brain, Zap,
  Maximize2, Minimize2, PenTool, Sparkles, Dumbbell, Waves, MessageCircle, Eye,
  BarChart3, Mic, TrendingUp, Users, RefreshCw, Search, BookOpen, Gauge, Heart,
  Lightbulb, UserPlus, MessagesSquare, ArrowRightLeft, Flame, Shuffle, HelpCircle,
  Globe, GitBranch, Clock, Layers, BookMarked, Theater, Volume2, FileText
} from 'lucide-react';
import { Tool, ToolCategory, CategoryMeta } from './types';

// ============================================================================
// CATEGORY METADATA
// ============================================================================

export const categoryMeta: Record<ToolCategory, CategoryMeta> = {
  generate: { name: 'Generate', color: 'emerald', description: 'Create new content' },
  enhance: { name: 'Enhance', color: 'blue', description: 'Improve existing text' },
  analyze: { name: 'Analyze', color: 'amber', description: 'Get insights on your writing' },
  brainstorm: { name: 'Brainstorm', color: 'purple', description: 'Generate ideas' },
  world: { name: 'World', color: 'rose', description: 'Build your story world' },
};

// ============================================================================
// ALL 44 TOOLS
// ============================================================================

export const tools: Tool[] = [
  // GENERATE TOOLS (6)
  {
    id: 'continue',
    name: 'Continue Writing',
    shortName: 'Cont',
    icon: Play,
    category: 'generate',
    description: 'Continue the story from where you left off',
  },
  {
    id: 'firstdraft',
    name: 'First Draft',
    shortName: 'Draft',
    icon: Zap,
    category: 'generate',
    description: 'Generate a quick first draft from an outline or idea',
  },
  {
    id: 'dialogue',
    name: 'Write Dialogue',
    shortName: 'Dial',
    icon: MessageSquare,
    category: 'generate',
    description: 'Generate character dialogue for a scene',
    isDynamic: true,
    dynamicSource: 'characters',
    hasSubMenu: true,
  },
  {
    id: 'description',
    name: 'Add Description',
    shortName: 'Desc',
    icon: Palette,
    category: 'generate',
    description: 'Add rich sensory details and descriptions',
    hasSubMenu: true,
    subOptions: [
      { id: 'setting', name: 'Setting/Environment' },
      { id: 'character', name: 'Character Appearance' },
      { id: 'action', name: 'Action/Movement' },
      { id: 'emotion', name: 'Emotional State' },
      { id: 'sensory', name: 'Full Sensory (5 senses)' },
    ],
  },
  {
    id: 'action',
    name: 'Action Scene',
    shortName: 'Actn',
    icon: Swords,
    category: 'generate',
    description: 'Write intense action sequences',
    hasSubMenu: true,
    subOptions: [
      { id: 'fight', name: 'Fight/Combat' },
      { id: 'chase', name: 'Chase Scene' },
      { id: 'escape', name: 'Escape/Pursuit' },
      { id: 'disaster', name: 'Disaster/Catastrophe' },
    ],
  },
  {
    id: 'thoughts',
    name: 'Inner Thoughts',
    shortName: 'Mind',
    icon: Brain,
    category: 'generate',
    description: 'Write internal monologue and character thoughts',
    isDynamic: true,
    dynamicSource: 'characters',
    hasSubMenu: true,
  },

  // ENHANCE TOOLS (8)
  {
    id: 'expand',
    name: 'Expand',
    shortName: 'Exp',
    icon: Maximize2,
    category: 'enhance',
    description: 'Expand selected text with more detail',
    requiresSelection: true,
    hasSubMenu: true,
    subOptions: [
      { id: 'detail', name: 'Add Details' },
      { id: 'emotion', name: 'Deepen Emotions' },
      { id: 'sensory', name: 'Add Sensory' },
      { id: 'backstory', name: 'Weave in Backstory' },
    ],
  },
  {
    id: 'condense',
    name: 'Condense',
    shortName: 'Cond',
    icon: Minimize2,
    category: 'enhance',
    description: 'Tighten and condense selected text',
    requiresSelection: true,
    hasSubMenu: true,
    subOptions: [
      { id: 'light', name: 'Light (10-20%)' },
      { id: 'moderate', name: 'Moderate (30-40%)' },
      { id: 'aggressive', name: 'Aggressive (50%+)' },
    ],
  },
  {
    id: 'rewrite',
    name: 'Rewrite',
    shortName: 'Rew',
    icon: RefreshCw,
    category: 'enhance',
    description: 'Rewrite selected text in a different style',
    requiresSelection: true,
    hasSubMenu: true,
    subOptions: [
      { id: 'dramatic', name: 'More Dramatic' },
      { id: 'subtle', name: 'More Subtle' },
      { id: 'faster', name: 'Faster Pace' },
      { id: 'slower', name: 'Slower Pace' },
      { id: 'custom', name: 'Custom Direction...' },
    ],
  },
  {
    id: 'polish',
    name: 'Polish',
    shortName: 'Pol',
    icon: Sparkles,
    category: 'enhance',
    description: 'Polish prose for better flow and word choice',
    requiresSelection: true,
  },
  {
    id: 'strengthen-verbs',
    name: 'Strengthen Verbs',
    shortName: 'Verb',
    icon: Dumbbell,
    category: 'enhance',
    description: 'Replace weak verbs with stronger alternatives',
    requiresSelection: true,
  },
  {
    id: 'vary-sentences',
    name: 'Vary Sentences',
    shortName: 'Vary',
    icon: Waves,
    category: 'enhance',
    description: 'Improve sentence variety and rhythm',
    requiresSelection: true,
  },
  {
    id: 'fix-dialogue-tags',
    name: 'Fix Dialogue Tags',
    shortName: 'Tags',
    icon: MessageCircle,
    category: 'enhance',
    description: 'Improve dialogue attribution and beats',
    requiresSelection: true,
  },
  {
    id: 'show-dont-tell',
    name: "Show Don't Tell",
    shortName: 'Show',
    icon: Eye,
    category: 'enhance',
    description: 'Convert telling into showing',
    requiresSelection: true,
  },

  // ANALYZE TOOLS (10)
  {
    id: 'pacing',
    name: 'Pacing Analysis',
    shortName: 'Pace',
    icon: BarChart3,
    category: 'analyze',
    description: 'Analyze chapter pacing and tension flow',
  },
  {
    id: 'voice-check',
    name: 'Voice Check',
    shortName: 'Voice',
    icon: Mic,
    category: 'analyze',
    description: 'Check narrative voice consistency',
  },
  {
    id: 'tension-map',
    name: 'Tension Map',
    shortName: 'Tens',
    icon: TrendingUp,
    category: 'analyze',
    description: 'Map tension levels throughout the chapter',
  },
  {
    id: 'character-voice',
    name: 'Character Voice',
    shortName: 'ChrV',
    icon: Users,
    category: 'analyze',
    description: 'Analyze character voice distinctiveness',
    isDynamic: true,
    dynamicSource: 'characters',
    hasSubMenu: true,
  },
  {
    id: 'repetition',
    name: 'Repetition Finder',
    shortName: 'Rep',
    icon: RefreshCw,
    category: 'analyze',
    description: 'Find repeated words and phrases',
  },
  {
    id: 'adverb-hunter',
    name: 'Adverb Hunter',
    shortName: 'Adv',
    icon: Search,
    category: 'analyze',
    description: 'Identify overused adverbs',
  },
  {
    id: 'passive-voice',
    name: 'Passive Voice',
    shortName: 'Pass',
    icon: Volume2,
    category: 'analyze',
    description: 'Find passive voice constructions',
  },
  {
    id: 'readability',
    name: 'Readability',
    shortName: 'Read',
    icon: Gauge,
    category: 'analyze',
    description: 'Assess reading level and clarity',
  },
  {
    id: 'emotional-arc',
    name: 'Emotional Arc',
    shortName: 'Emo',
    icon: Heart,
    category: 'analyze',
    description: 'Track emotional journey through the chapter',
  },
  {
    id: 'chapter-summary',
    name: 'Chapter Summary',
    shortName: 'Sum',
    icon: FileText,
    category: 'analyze',
    description: 'Generate a concise chapter summary',
  },

  // BRAINSTORM TOOLS (8)
  {
    id: 'plot-ideas',
    name: 'Plot Ideas',
    shortName: 'Plot',
    icon: Lightbulb,
    category: 'brainstorm',
    description: 'Generate plot ideas and directions',
    hasSubMenu: true,
    subOptions: [
      { id: 'next', name: 'What happens next?' },
      { id: 'conflict', name: 'Add conflict' },
      { id: 'complication', name: 'Add complications' },
      { id: 'resolution', name: 'Resolution ideas' },
    ],
  },
  {
    id: 'character-moments',
    name: 'Character Moments',
    shortName: 'Char',
    icon: UserPlus,
    category: 'brainstorm',
    description: 'Generate meaningful character moments',
    isDynamic: true,
    dynamicSource: 'characters',
    hasSubMenu: true,
  },
  {
    id: 'dialogue-options',
    name: 'Dialogue Options',
    shortName: 'DiaO',
    icon: MessagesSquare,
    category: 'brainstorm',
    description: 'Generate dialogue alternatives',
    requiresSelection: true,
  },
  {
    id: 'scene-transitions',
    name: 'Scene Transitions',
    shortName: 'Trans',
    icon: ArrowRightLeft,
    category: 'brainstorm',
    description: 'Suggest scene transition approaches',
  },
  {
    id: 'conflict-escalation',
    name: 'Conflict Escalation',
    shortName: 'Conf',
    icon: Flame,
    category: 'brainstorm',
    description: 'Ways to escalate conflict and tension',
  },
  {
    id: 'twist-generator',
    name: 'Twist Generator',
    shortName: 'Twist',
    icon: Shuffle,
    category: 'brainstorm',
    description: 'Generate surprising plot twists',
    hasSubMenu: true,
    subOptions: [
      { id: 'betrayal', name: 'Betrayal twist' },
      { id: 'revelation', name: 'Hidden truth revealed' },
      { id: 'reversal', name: 'Situation reversal' },
      { id: 'unexpected', name: 'Unexpected ally/enemy' },
    ],
  },
  {
    id: 'what-if',
    name: 'What If...',
    shortName: 'What',
    icon: HelpCircle,
    category: 'brainstorm',
    description: 'Explore "what if" scenarios',
  },
  {
    id: 'stuck-help',
    name: "I'm Stuck",
    shortName: 'Stuck',
    icon: HelpCircle,
    category: 'brainstorm',
    description: 'Get help when you are stuck',
  },

  // WORLD TOOLS (6)
  {
    id: 'characters',
    name: 'Characters',
    shortName: 'Char',
    icon: Users,
    category: 'world',
    description: 'Manage your story characters',
  },
  {
    id: 'locations',
    name: 'Locations',
    shortName: 'Loc',
    icon: Globe,
    category: 'world',
    description: 'Manage story locations',
  },
  {
    id: 'plot-threads',
    name: 'Plot Threads',
    shortName: 'Thrd',
    icon: GitBranch,
    category: 'world',
    description: 'Track plot threads and subplots',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    shortName: 'Time',
    icon: Clock,
    category: 'world',
    description: 'Story timeline and events',
  },
  {
    id: 'scene-contexts',
    name: 'Scene Contexts',
    shortName: 'Scene',
    icon: Layers,
    category: 'world',
    description: 'Create sensory palettes for scenes',
  },
  {
    id: 'story-bible',
    name: 'Story Bible',
    shortName: 'Bible',
    icon: BookMarked,
    category: 'world',
    description: 'Your complete story reference',
  },
];

// Helper to get tools by category
export const getToolsByCategory = (category: ToolCategory): Tool[] => {
  return tools.filter(t => t.category === category);
};

// Helper to get a tool by ID
export const getToolById = (id: string): Tool | undefined => {
  return tools.find(t => t.id === id);
};
